 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace YTC2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestSignUp = (Nettention.Proud.RmiID)12000+1;
			public const Nettention.Proud.RmiID RequestSignIn = (Nettention.Proud.RmiID)12000+2;
			public const Nettention.Proud.RmiID RequestNicknameUsable = (Nettention.Proud.RmiID)12000+3;
			public const Nettention.Proud.RmiID RequestRoomCreate = (Nettention.Proud.RmiID)12000+4;
			public const Nettention.Proud.RmiID RequestRoomJoin = (Nettention.Proud.RmiID)12000+5;
			public const Nettention.Proud.RmiID RequestRoomLeave = (Nettention.Proud.RmiID)12000+6;
			public const Nettention.Proud.RmiID RequestRoomList = (Nettention.Proud.RmiID)12000+7;
			public const Nettention.Proud.RmiID RequestRoomUserList = (Nettention.Proud.RmiID)12000+8;
			public const Nettention.Proud.RmiID SystemChat = (Nettention.Proud.RmiID)12000+9;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestSignUp,
			RequestSignIn,
			RequestNicknameUsable,
			RequestRoomCreate,
			RequestRoomJoin,
			RequestRoomLeave,
			RequestRoomList,
			RequestRoomUserList,
			SystemChat,
		};
	}
}






				 
