 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace UserProtocol
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestSignin = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID NotifySigninSuccess = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID NotifySigninFailed = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID RequestLogin = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID NotifyLoginSuccess = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID NotifyLoginFailed = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID ResponseLogin = (Nettention.Proud.RmiID)2000+7;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestSignin,
			NotifySigninSuccess,
			NotifySigninFailed,
			RequestLogin,
			NotifyLoginSuccess,
			NotifyLoginFailed,
			ResponseLogin,
		};
	}
}
namespace RoomProtocol
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestRoomCreate = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID NotifyRoomCreateSuccess = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID NotifyRoomCreateFailed = (Nettention.Proud.RmiID)3000+3;
			public const Nettention.Proud.RmiID RequestRoomList = (Nettention.Proud.RmiID)3000+4;
			public const Nettention.Proud.RmiID ResponseRoomList = (Nettention.Proud.RmiID)3000+5;
			public const Nettention.Proud.RmiID RequestRoomUserList = (Nettention.Proud.RmiID)3000+6;
			public const Nettention.Proud.RmiID ResponseRoomUserList = (Nettention.Proud.RmiID)3000+7;
			public const Nettention.Proud.RmiID RequestRoomJoin = (Nettention.Proud.RmiID)3000+8;
			public const Nettention.Proud.RmiID NotifyRoomJoinSuccess = (Nettention.Proud.RmiID)3000+9;
			public const Nettention.Proud.RmiID NotifyRoomJoinFailed = (Nettention.Proud.RmiID)3000+10;
			public const Nettention.Proud.RmiID RequestRoomLeave = (Nettention.Proud.RmiID)3000+11;
			public const Nettention.Proud.RmiID NotifyRoomLeaveSuccess = (Nettention.Proud.RmiID)3000+12;
			public const Nettention.Proud.RmiID NotifyRoomLeaveFailed = (Nettention.Proud.RmiID)3000+13;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestRoomCreate,
			NotifyRoomCreateSuccess,
			NotifyRoomCreateFailed,
			RequestRoomList,
			ResponseRoomList,
			RequestRoomUserList,
			ResponseRoomUserList,
			RequestRoomJoin,
			NotifyRoomJoinSuccess,
			NotifyRoomJoinFailed,
			RequestRoomLeave,
			NotifyRoomLeaveSuccess,
			NotifyRoomLeaveFailed,
		};
	}
}
namespace ChatProtocol
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID P2PChat = (Nettention.Proud.RmiID)4000+1;
			public const Nettention.Proud.RmiID SystemChat = (Nettention.Proud.RmiID)4000+2;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			P2PChat,
			SystemChat,
		};
	}
}
namespace ItemProtocol
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestItemAdd = (Nettention.Proud.RmiID)5000+1;
			public const Nettention.Proud.RmiID NotifyItemAddSuccess = (Nettention.Proud.RmiID)5000+2;
			public const Nettention.Proud.RmiID NotifyItemAddFailed = (Nettention.Proud.RmiID)5000+3;
			public const Nettention.Proud.RmiID RequestItemList = (Nettention.Proud.RmiID)5000+4;
			public const Nettention.Proud.RmiID ResponseItemList = (Nettention.Proud.RmiID)5000+5;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestItemAdd,
			NotifyItemAddSuccess,
			NotifyItemAddFailed,
			RequestItemList,
			ResponseItemList,
		};
	}
}






				 
