 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace YTS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ResponseSignUp = (Nettention.Proud.RmiID)11000+1;
			public const Nettention.Proud.RmiID ResponseSignIn = (Nettention.Proud.RmiID)11000+2;
			public const Nettention.Proud.RmiID ResponseNicknameUsable = (Nettention.Proud.RmiID)11000+3;
			public const Nettention.Proud.RmiID ResponseRoomCreate = (Nettention.Proud.RmiID)11000+4;
			public const Nettention.Proud.RmiID ResponseRoomJoin = (Nettention.Proud.RmiID)11000+5;
			public const Nettention.Proud.RmiID ResponseRoomLeave = (Nettention.Proud.RmiID)11000+6;
			public const Nettention.Proud.RmiID ResponseRoomList = (Nettention.Proud.RmiID)11000+7;
			public const Nettention.Proud.RmiID SystemChat = (Nettention.Proud.RmiID)11000+8;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ResponseSignUp,
			ResponseSignIn,
			ResponseNicknameUsable,
			ResponseRoomCreate,
			ResponseRoomJoin,
			ResponseRoomLeave,
			ResponseRoomList,
			SystemChat,
		};
	}
}






				 
